name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image for frontend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-app --build-arg VITE_NODE_ENV='production' --build-arg VITE_API_URL='${{ secrets.VITE_API_URL }}:${{secrets.AWS_BACKEND_PORT}}' --build-arg VITE_DOCKER_NGINX_PORT='${{secrets.VITE_DOCKER_NGINX_PORT}}'  ./my-frontend
      - name: Build Docker Image for backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app --build-arg DOCKER_BACKEND_PORT='${{secrets.DOCKER_BACKEND_PORT}}'  ./my-backend
      - name: Publish Frontend Image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest
      - name: Publish Backend Image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull frontend image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest
      - name: Pull backend image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
      - name: Delete frontend old container
        run: docker rm -f reactjs-app-container
      - name: Delete backend old container
        run: docker rm -f nodejs-app-container
      - name: Run Frontend Docker Container
        run: docker run -d -p ${{secrets.AWS_FRONTEND_PORT}}:${{secrets.VITE_DOCKER_NGINX_PORT}} --name reactjs-app-container ${{ secrets.DOCKER_USERNAME }}/reactjs-app
      - name: Run Backend Docker Container
        run: docker run -d -p ${{secrets.AWS_BACKEND_PORT}}:${{secrets.DOCKER_BACKEND_PORT}} --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' -e DOCKER_BACKEND_PORT='${{secrets.DOCKER_BACKEND_PORT}}' ${{ secrets.DOCKER_USERNAME }}/nodejs-app
